# Generated by Django 2.1 on 2019-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=30)),
                ('order_type', models.CharField(max_length=20)),
                ('order_status', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=10)),
                ('remark', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=None)),
                ('timestamp', models.DateTimeField(default=True)),
            ],
        ),
    ]
